Support ES6 Module Imports [NAJ-181, NAJ-52]
near/near-api-js pull request #1011
Opened 2022-10-07 02:04 UTC by hcho112

## Motivation
To support ES6 Module Imports 

## Description
This PR introduces a new bundler called [tsup](https://tsup.egoist.dev/) that is recommended by [turborepo](https://turborepo.org/docs/handbook/publishing-packages/bundling)

It will produce `index.js` (CJS), `index.mjs` (ESM) and `index.d.ts` (Type) under `/dist` folder as result of build. 

For due diligence, I have contacted small experiment by forking the NAJ into a [seperate repo](https://github.com/hcho112/near-api-js) that has already merged this commit, and published to a independent [npm package](https://www.npmjs.com/package/near-api-js-danny) and tried few examples to see if everything work as normal.

So far everything worked as normal.

Closes #798

## Checklist
- [ ] Read the [contributing](https://github.com/near/near-api-js/blob/master/CONTRIBUTING.md) guidelines
- [ ] Commit messages follow the [conventional commits](https://www.conventionalcommits.org/) spec
- [ ] Performed a self-review of the PR
- [ ] Added automated tests
- [ ] Manually tested the change

2022-10-24 19:07 UTC, andy-haynes requested changes
This is a good first step in the right direction but we need to ensure we're choosing the right bundler and not breaking our current publishing strategy and preventing certain (e.g. web CDN) consumers from using future versions.

Overall I think there is some confusion as to exactly which import contexts we want to support. Users would benefit from documentation around the supported import contexts with accompanying code examples we can reference. For example:
- CommonJS imports from node < 18
- native module imports from node > 18
- `<script>` imports from the NPM CDN
- browser ESM

I don't think these need any more than a brief description on the import context and a snippet of code showing the import + some basic functionality (e.g. calling a view function). But it would go a long way towards helping developers by being explicit about what we support and gives us acceptance criteria for the introduction of whatever publishing strategy satisfies them.

2022-10-25 01:23 UTC, hcho112 commented on packages/near-api-js/package.json
> +        "tsup": "^6.2.3",
Thank you for detailed feedback. After reviewing your feedback, I starting to think that `tsup` may not be the best choice to support `Support ES6 Module Imports` task. Will continue search for better tools (unopinionated, should be able to use/refer existing tsconfig.json) to support this

2024-01-08 14:42 UTC, vikinatora commented
Hey everyone, I'm currently conducting a clean-up on the issues of NAJ. From my perspective, this PR seems no longer relevant. Please let me know if that's not the case - I'll create an issue to track the progress; otherwise, I'll proceed to close the PR in 5 days.

2024-01-10 19:51 UTC, andy-haynes commented
> Hey everyone, I'm currently conducting a clean-up on the PRs of NAJ. From my perspective, this PR seems no longer relevant. Please let me know if that's not the case - I'll create an issue to track the progress; otherwise, I'll proceed to close the PR in 5 days.

This PR is dead but I imagine the #798 issue is still relevant despite having been closed by automated tooling.

2024-01-10 19:51 UTC, closed without merging

2024-01-11 11:29 UTC, vikinatora commented
@andy-haynes Sure, we will check #798 out.