Feat/meta transactions
near/near-api-js pull request #1097
Opened 2023-04-01 01:51 UTC by andy-haynes

This PR implements functionality for delegate actions and meta transactions for [NEP 366: Meta Transactions](https://github.com/near/NEPs/blob/master/neps/nep-0366.md).

For `@near-js/transactions`, this adds:
- new action classes and creator for `DelegateAction` actions
- methods for constructing, signing, and encoding `DelegateAction`s
- new schema entries for `DelegateAction`
- new classes for [NEP 461](https://github.com/near/NEPs/pull/461) prefixes

In `@near-js/accounts` I've added `Account` methods:
- `signedDelegate` builds and signs a delegate action
- `signAndSendMetaTransaction` builds and signs a meta transaction derived from the delegate action

A new cookbook example in included to demonstrate the usage of the new `Account` methods.

2023-04-01 01:59 UTC, andy-haynes commented on packages/transactions/src/schema.ts
> +}
Initially I wanted to opportunistically refactor the Transaction and SignedTransaction classes to decouple the class definitions from SCHEMA, but ultimately decided it was too much unrelated effort for a half measure.

I opted to leave these new methods in place and use them in favor of the encode/decode class methods but they're not strictly relevant to this PR.

2023-04-03 21:24 UTC, andy-haynes commented on packages/accounts/src/account.ts
> +const DEFAULT_META_TRANSACTION_BLOCK_HEIGHT_TTL = 600;
Is it helpful to have a default in the client? (ideally co-located with other relayer configuration)

2023-04-03 21:33 UTC, andy-haynes commented on packages/accounts/src/account.ts
> +        return fetchJson(relayerUrl, JSON.stringify(Array.from(encodeSignedDelegate(signedDelegate))));
Current implementation of relayers requires the JSON body be a serialized byte array (i.e. not wrapped in an object).

NEP-366 describes an interface for this, so it's possible the implementation will change:
```rs
struct DelegateActionMessage {
    signed_delegate_action: SignedDelegateAction
}
```

> - User forms `DelegateActionMessage` with the `SignedDelegateAction`.
> - User sends `DelegateActionMessage` data to the relayer.

2023-04-03 21:34 UTC, andy-haynes commented on packages/cookbook/transactions/meta-transaction-relayer.js
> +    sendNearThroughRelayer,
I created the `cookbook` examples from a new template from an in-review PR that supports testing snippets here. When that PR is landed I can add integration tests for these.

2023-04-10 20:32 UTC, andy-haynes commented on packages/transactions/src/sign.ts
> +    sign(message: Uint8Array): Promise<Uint8Array>;
I'm not super attached to this, it was just my way of inching away from coupling transaction signing methods and network while avoiding stepping into the current state of keystores and their 1:1 account-network mapping. Definitely open to alternatives or tweaks to this approach.

2023-04-12 20:52 UTC, morgsmccauley reviewed
Good job on this! Most looks good, just a couple questions around the necessity of some parts :)

2023-04-12 20:53 UTC, morgsmccauley commented
sorry misclick

2023-04-12 21:43 UTC, andy-haynes commented on .changeset/lovely-balloons-talk.md
> +Add support for delegate actions and meta transactions
Interesting, I made the distinction mostly in the context of relayers:
- **delegate action** is an action signed by the relay caller
- **meta transaction** is a transaction signed by the relayer

I omitted the hyphen to reflect its title and usage in [NEP 366](https://github.com/near/NEPs/blob/master/neps/nep-0366.md)

2023-04-12 21:53 UTC, andy-haynes commented on packages/accounts/src/account.ts
> +    async signAndSendMetaTransaction(signedDelegate: SignedDelegate): Promise<FinalExecutionOutcome> {
That makes sense, I will move it to the cookbook.

2023-04-12 21:55 UTC, andy-haynes commented on packages/transactions/src/delegated.ts
I like it 😎

2023-04-12 22:16 UTC, andy-haynes commented on packages/accounts/src/account.ts
> +    async signAndSendSignedDelegate({
That's a good point, I think to do this right you'd want a relayer interface that could be extended to talk to non-REST endpoints. Given the nascent stage of things it's best not to have strong opinions up front 😄

2023-04-13 01:25 UTC, morgsmccauley submitted a review, later dismissed
Good job 👏

2023-04-13 12:41 UTC, MaximusHaximus requested changes
Nice work -- looking good.  Just spotted a few things which I added comments about in-line and was thinking about some naming tweaks.

Just one thing that I noticed while looking through the PR was the DelegateAction type being local to the transactions package -- I would've expected it to be in the `@near-js/types` package which has a Transaction type that would need to reference all of the action types for accuracy.

I think to avoid circular references between the types package and the rest of the packages we're going to need to pull almost all of the types into the types package and only keep internal/local types in the individual packages that use the @near-js/types package -- I think this is why a Transaction type exists in the types package, but because Action types don't, the Transaction type in the types package defines `actions` as an <any> type.  We should have a chat about this and it's not any kind of a blocker for this PR to land for us to iterate on.

2023-04-13 12:41 UTC, MaximusHaximus commented on packages/transactions/src/delegate.ts
> +    maxBlockHeight: number;
I think this must be a BN type also; block heights can be huge (U64), and looking at the code below we do use BN to set this property

2023-04-13 12:41 UTC, MaximusHaximus commented on packages/transactions/src/actions.ts
> +import { Signature } from './signature.js';
Should these file extensions be .ts?

2023-04-13 12:41 UTC, MaximusHaximus commented on packages/transactions/src/delegate.ts
> +} from './actions.js';
Should this file extension be .ts?

2023-04-13 12:41 UTC, MaximusHaximus commented on packages/transactions/src/prefix.ts
> + * @todo uncomment when off-chain messages are supported
Is there an NEP, release version or date where we expect this to be true that we could reference here, or is this an indefinite 'some day' kind of thing? :)

2023-04-13 16:57 UTC, andy-haynes commented on packages/transactions/src/schema.ts
> +        ['actions', [Action]],
`DelegableAction` is a union type but a class is required here.

2023-04-13 17:48 UTC, andy-haynes commented on packages/transactions/src/delegate.ts
> +export type NonDelegateAction =
Looking at it more closely I see it's actually ignoring the union types altogether:
- `{ actions: Array<AddKey> }`  => `actions = [new SignedDelegate({})]` ❌ 
- `{ actions: Array<AddKey | DeleteKey> }`  => `actions = [new SignedDelegate({})]` ✅ 

It looks like by having a union with > 1 members, the common shape is demoted to their common `Assignable` base class and so anything with `constructor(properties: any)` will pass the union. This wasn't something I knew about union types 💡 

So with the current implementation being set dressing, I think options are:
- double down on this approach and incorporate delegability into the class hierarchy
- implement the chain-side logic in the client with runtime checks that throw exceptions when a non-delegate action is added to the signed delegate
- ignore for now and let the chain fail them

2023-04-13 18:08 UTC, andy-haynes commented
> we're going to need to pull almost all of the types into the types package and only keep internal/local types in the individual packages that use the @near-js/types package

The crux of the issue is that many of these are classes implementing methods with heavy dependencies not appropriate for `@near-js/types`. `Transaction` is a good example but `PublicKey` is even better. To do it cleanly requires another substantial refactor with breaking changes.

>  I think this is why a Transaction type exists in the types package, but because Action types don't, the Transaction type in the types package defines actions as an type. 

The `Transaction` type in `@near-js/types` is a duplicate definition that originally came from the `providers.ts` file before the refactor. They should be merged when appropriate.

2023-04-13 19:54 UTC, MaximusHaximus commented on packages/transactions/src/delegate.ts
> +export type NonDelegateAction =
Let's let the chain fail them and re-visit the classes later for ideal typesafety :+1:

2023-04-13 21:46 UTC, MaximusHaximus approved these changes
:+1: I think this is shippable at this stage 💖

2023-04-13 22:06 UTC, merged