Remove buggy dependencies
near/near-api-js pull request #1224
Opened 2023-12-21 13:29 UTC by gtsonevv

## Pre-flight checklist

- [ ] I have read the [Contributing Guidelines on pull requests](https://github.com/near/near-api-js/blob/master/CONTRIBUTING.md).
- [ ] Commit messages follow the [conventional commits](https://www.conventionalcommits.org/) spec
- [ ] **If this is a code change**: I have written unit tests.
- [ ] **If this changes code in a published package**: I have run `pnpm changeset` to create a `changeset` JSON document appropriate for this change.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

## Test Plan

## Related issues/PRs

https://github.com/near/near-api-js/pull/1217
https://github.com/near/near-api-js/issues/1200

2023-12-21 14:13 UTC, vikinatora requested changes

2023-12-21 14:13 UTC, vikinatora commented on packages/signers/package.json
> +    "@noble/hashes": "^1.3.3"
Please lock the version

2023-12-21 14:13 UTC, vikinatora commented on packages/transactions/package.json
> +    "@noble/hashes": "^1.3.3"
Same comment

2023-12-21 14:13 UTC, vikinatora commented on packages/near-api-js/src/browser-index.ts
> -import 'error-polyfill';
I think it's fine to leave error-polyfill

2023-12-21 15:09 UTC, vikinatora commented on packages/near-api-js/src/browser-index.ts
> -import 'error-polyfill';
Disregard the comment

2023-12-21 15:10 UTC, vikinatora submitted a review, later dismissed

2024-01-02 10:22 UTC, gagdiez approved these changes

2024-01-03 08:25 UTC, vikinatora approved these changes

2024-01-03 08:25 UTC, merged