fix: view function use buffer
near/near-api-js pull request #1356
Opened 2024-06-26 09:14 UTC by hanakannzashi

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/near/near-api-js/blob/master/CONTRIBUTING.md).
- [x] Commit messages follow the [conventional commits](https://www.conventionalcommits.org/) spec
- [x] **If this is a code change**: I have written unit tests.
- [ ] **If this changes code in a published package**: I have run `pnpm changeset` to create a `changeset` JSON document appropriate for this change.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Same as call function, view function should also allow `Buffer` as args

2024-07-10 17:30 UTC, andy-haynes requested changes
Thank you for the PR @hanakannzashi! Please address the feedback on your change so we can get this included in an upcoming release.

> I have run `pnpm changeset` to create a `changeset` JSON document appropriate for this change.

Please be sure to follow this step and include the changeset document in your PR. I believe this is just a `patch` change, no?

2024-07-10 17:30 UTC, andy-haynes commented on packages/accounts/src/utils.ts
> +export function stringifyJsonOrBytes(args: any): Buffer {
This method is already exported from `@near-js/transactions`, please import it from there and remove `bytesJsonStringify`.

2024-07-10 17:32 UTC, andy-haynes commented
@race-of-sloths 👋

2024-07-10 17:33 UTC, race-of-sloths commented
@hanakannzashi Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
New Sloth joined the Race! Welcome!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/hanakannzashi?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/hanakannzashi?type=bot&theme=light">
    <img alt="Shows profile picture for the author of the PR" src="https://badge.race-of-sloths.com/hanakannzashi?type=bot&theme=white">
</picture>](https://race-of-sloths.com/profile/hanakannzashi)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/hanakannzashi)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

2024-07-10 17:35 UTC, andy-haynes commented
@race-of-sloths score 2

2024-07-10 17:36 UTC, race-of-sloths commented
### 🌟 Score recorded!

@andy-haynes, thank you for scoring this pull request in the Race of Sloths!

2024-07-25 18:01 UTC, race-of-sloths commented
### ❌ PR inactive
This PR has been inactive for two weeks. It's now marked as stale. 
>[!TIP]
If you think it's a mistake, you can restart the bot with `include` command to proceed 🔄

2025-01-06 11:49 UTC, closed without merging