leave ledger key untouched when deployMutlisig
near/near-api-js pull request #444
Opened 2020-10-31 02:00 UTC by mattlockyer

This PR filters out ledger key from keys that are converted to limited access keys, when user deploys multisig contract.

2020-11-03 09:08 UTC, vgrichina commented
@mattlockyer looks good, but please add regression test

2020-11-03 09:27 UTC, vgrichina requested changes
Needs a test demonstrating fixed bug

2020-11-06 10:23 UTC, vgrichina commented on test/test-utils.js
> +async function createAccount(near, str = 'test') {
not sure what is the reason for the change? Does it matter for test what is account name prefix?

2020-11-06 10:27 UTC, vgrichina commented on test/account.test.js
> +                throw(e);
nit: it's `throw e;`

2020-11-06 10:30 UTC, vgrichina commented on test/account.test.js
> +            data: originalKeys.map(({ public_key: publicKey }, i) => ({ publicKey, kind: i > 0 ? 'ledger' : 'phrase' }))
there should be non-ledger and non-phrase key as well to test that it gets converted properly

2020-11-06 10:30 UTC, vgrichina commented on test/account.test.js
> +        expect(currentKeys[0].access_key.permission).toEqual('FullAccess');
this should check that public keys are as desired as well

2020-11-18 18:39 UTC, mattlockyer commented
Merged in #453

2020-11-18 18:39 UTC, closed without merging